language: ruby
before_install:
- eval `ssh-agent -s`
- curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
- nvm install 6
- npm install npm@5 -g
- gem update --system
before_script:
- npm install
script: node deploy .
