dist: trusty
sudo: false
language: node_js
node_js:
  - 6
before_install:
# Ensure there is an ssh-agent running
- eval `ssh-agent`
# Ensure NPM 5
- npm install npm@5 -g
# Bundler for Jekyll
- gem install bundler
script: node deploy .
